server:
  port: 8050
spring:
  application:
    name: consumer-zuul
eureka:
  client:
    service-url:
      defaultZone: http://user:123123@localhost:8761/eureka/
logging:
  level:
    root: info
zuul:
  routes:
    sidecar-app:
      path: /car/**
      serviceId: sidecar
    user-app:
      path: /user/**
      serviceId: provider-user


